#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-407670.okta.com/oauth2/default

#  cloud:
#    consul:
#      discovery:
#        health-check-interval: 1m
